HTM-733, HTM-736, HTM-739 and HTM-740
OpenRedButtonProject/orb pull request #251
Opened 2024-01-23 10:13 UTC by ivanqin-obs

Description:

- (The receiver should not process voice command through orbsessioncallback) removed in HTM-740
- Send data directly to orbsession
- Renaming the voice command function
- Update onVoiceSendKeyAction to dispatch key event
- Remove dispatchKeyPressEvent and notifyKeyUp
- Move voice service receiver to TIS (as well as mainactivity in mockapp)
- Create interface default method for consoleLog in session callback

2024-01-25 15:10 UTC, joshua-h requested changes

2024-01-25 15:10 UTC, joshua-h commented on android/orblibrary/src/main/java/org/orbtv/orblibrary/OrbSession.java
> +    private String MOCK_NEW_MEDIA_ID = "urn:broadcaster:programme:1249863457643";
Why would we have a "MOCK" property in the main ORB library?

2024-01-25 15:10 UTC, joshua-h commented on android/orblibrary/src/main/java/org/orbtv/orblibrary/IOrbSessionCallback.java
> +    default void consoleLog(String log) {
If this is only used for 204, can we throw an exception if it's not implemented, and implement it in the mock204app instead, to be consistent with other methods.

2024-01-30 15:52 UTC, joshua-h requested changes

2024-01-30 15:52 UTC, joshua-h commented on android/orblibrary/src/main/java/org/orbtv/orblibrary/IOrbSessionCallback.java
> +    default String get_MEDIA_ID(String name) {
Please use a consistent style, `e.g., getMediaId(String name)`

2024-01-30 15:52 UTC, joshua-h commented on android/orblibrary/src/main/java/org/orbtv/orblibrary/IOrbSessionCallback.java
> +        Log.d("IOrbSessionCallback", "consoleLog: " + log);
This Log.d can be deleted. This class should be overriden by an implementation.

2024-01-30 15:52 UTC, joshua-h commented on android/orblibrary/src/main/java/org/orbtv/orblibrary/IOrbSessionCallback.java
> +import android.util.Log;
Can be deleted

2024-01-30 16:49 UTC, ivanqin-obs commented on android/orblibrary/src/main/java/org/orbtv/orblibrary/IOrbSessionCallback.java
> +import android.util.Log;
Have done these changes

2024-01-31 13:37 UTC, merged