HTM-783 Dialogue Enhancement Update and Revised Ordering
OpenRedButtonProject/orb pull request #295
Opened 2024-03-26 09:35 UTC by ivanqin-obs

Description:
- Addressed issue where dialogueEnhancementGain being 0 is now removed.
- Adjusted dialogue enhancement override process to ensure receiving one response message and a notification. The order has been updated, with the notification coming after the response.

Testing:
- Build image
- org.hbbtv_AC4-DE0120
- org.hbbtv_AC4-DE0110
- org.hbbtv_AC4-DE0160
- org.hbbtv_AC4-DE0003
- org.hbbtv_AC4-DE0080
- org.hbbtv_AC4-DE0070

2024-03-26 10:22 UTC, joshua-h approved these changes

2024-03-26 10:22 UTC, joshua-h commented
Happy to merge unless @LiyunOBS has any comments

2024-03-26 11:31 UTC, LiyunOBS requested changes

2024-03-26 11:31 UTC, LiyunOBS commented on android/mock204app/src/main/java/org/orbtv/mock204app/MockOrbSessionCallback.java
> -            appliedGain = MOCK_DIALOGUE_ENHANCEMENT_GAIN;
It seems the status must be updated if the gain is overridden to 0?
```
dialogueEnhancementGain – This optional integer number specifies, when present, the requested gain value in
dB of the dialogue enhancement processing to be applied in the audio decoder. A value of 0 shall disable the dialogue
enhancement processing.
```

2024-03-26 11:31 UTC, LiyunOBS commented on android/mock204app/src/main/java/org/orbtv/mock204app/MockOrbSessionCallback.java
> +        }
I'm fine with the swapping the codes
Could you check it's with the same logic with your code, or any other thing I didn't think of?
```
        mSession.onRespondDialogueEnhancementOverride(connection, id, appliedGain);
        consoleLog("Apply dialogue enhancement override, gain: " + appliedGain);
        boolean isValueChanged = false;
        if (MOCK_DIALOGUE_ENHANCEMENT_GAIN != appliedGain) {
            MOCK_DIALOGUE_ENHANCEMENT_GAIN = appliedGain;
            consoleLog("Apply dialogue enhancement");
            boolean isEnabled = Boolean.TRUE.equals(MOCK_ENABLE_STATUS.get(F_DIALOGUE_ENHANCEMENT));
            notifyDialogueEnhancement(isEnabled);
            consoleLog("Notify settings of dialogue enhancement, gain: " +
                    (isEnabled ? MOCK_DIALOGUE_ENHANCEMENT_GAIN : 0));
        }
        ```

2024-03-27 11:28 UTC, ivanqin-obs commented
Ready to merge. @joshua-h

2024-04-03 18:08 UTC, merged